### ISSUE TITLE
Пояснение

### ISSUE THREAD

**Issue by sssergy** [Houzich/Brute-Force-Private-Key-CUDA#1]
То есть эта программа ищет только начало WIF? 
А если, например, утеряны данные в середине или в конце ключа?

**Comment by sssergy** [comment]
Да, кстати, этот софт только под винду. Будет ли вариант под линукс?

**Comment by Houzich** [comment]
Да, в этой версии, программа ищет только утерянное начало ключа. В следующих версиях будет возможность искать в любом месте ключа.

**Comment by sssergy** [comment]
Будем ждать )
Все же хотелось бы версию под иксы.

**Comment by dextronomous** [comment]
Hi thanks for the great program, could you maybe make a debug output or verbose so we can see how and what is scanned. would be great if possible.
